name: 'ci'

on:
  push:
    branches: main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Send job start webhook
        continue-on-error: true
        uses: appleboy/discord-action@4c19612
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: Starting build for commit ${{ github.sha }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          # github username and personal access token
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2.1.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          # Can't auto-push with v2 right now...
          tags: ghcr.io/ihaveamac/kurisu:latest
          build-args: COMMIT=${{ github.sha }},BRANCH=${{ github.ref }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Send push webhook
        continue-on-error: true
        uses: appleboy/discord-action@4c19612
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: Pushing to ghcr.io/nh-server/kurisu
      - name: Push Docker image
        run: docker push ghcr.io/ihaveamac/kurisu:latest
# https://stackoverflow.com/questions/60477061/github-actions-how-to-deploy-to-remote-server-using-ssh/60479844#60479844
#      - name: Create SSH key
#        run: |
#          mkdir -p ~/.ssh/
#          chmod 700 ~/.ssh/
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
#        shell: bash
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
#      - name: Send push webhook
#        continue-on-error: true
#        uses: appleboy/discord-action@4c19612
#        with:
#          webhook_id: ${{ secrets.WEBHOOK_ID }}
#          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
#          message: Pulling on server
#      - name: Pull on server
#        run: docker-compose pull
#        env:
#          DOCKER_HOST: ${{ secrets.SSH_HOST }}
#      - name: Send up webhook
#        continue-on-error: true
#        uses: appleboy/discord-action@4c19612
#        with:
#          webhook_id: ${{ secrets.WEBHOOK_ID }}
#          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
#          message: Running on server
#      - name: Run on server
#        run: docker-compose up -d
#        env:
#          DOCKER_HOST: ${{ secrets.SSH_HOST }}
